# BUILD STAGE
FROM node:18-alpine as build

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm build

#SERVE STAGE
FROM node:18-alpine

# Copy the built app from the previous stage to the Nginx server
COPY --from=build /app/build /app

EXPOSE 3000

# Default command to start Nginx
#CMD ["nginx", "-g", "daemon off;"]
CMD ["npm", "start"]
