# version: "3.7"

services:
  frontend:
    build: ./client
    image: nogadocker/frontend:latest
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./client/src/.env

  backend:
    build: ./server
    image: nogadocker/backend:latest
    ports:
      - "8000:8000"

    env_file:
      - ./server/.env
